apiVersion: v1
kind: Service
metadata:
  name: machinelearn-service
spec:
  type: NodePort
  selector:
    app: machinelearn
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30080
      
